name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ExpressJs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh i
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/rsa_ghdk_api
            cd /api 
            git checkout main
            git pull origin main
            docker stop expressjs-api
            docker rm expressjs-api
            docker-compose build
            docker-compose up -d
            docker logs expressjs-api